dynamictp.enabled=true                                  # ???? dynamictp???true
dynamictp.enabledCollect=true                           # ?????????????true
dynamictp.collectorTypes=micrometer,logging             # ??????????logging | micrometer | internal_logging | JMX????micrometer
dynamictp.logPath=/home/logs/dynamictp/user-center/    # ??????????? ${user.home}/logs??????logging????
dynamictp.monitorInterval=5                             # ????????????????????5s

# ????
dynamictp.platforms[0].platform=wechat                  # ??????????
dynamictp.platforms[0].platformId=1                     # ??id????
dynamictp.platforms[0].urlKey=3a700-127-4bd-a798-c53d8b69c # webhook ?? key
dynamictp.platforms[0].receivers=test1,test2            # ???????

dynamictp.platforms[1].platform=ding                    # ??????????
dynamictp.platforms[1].platformId=2                     # ??id????
dynamictp.platforms[1].urlKey=f80dad441fcd655438f4a08dcd6a # webhook ?? access_token
dynamictp.platforms[1].secret=SECb5441fa6f375d5b9d21    # ????????????????????????
dynamictp.platforms[1].receivers=18888888888            # ???????

dynamictp.platforms[2].platform=lark                    # ??????????
dynamictp.platforms[2].platformId=3                     # ??id????
dynamictp.platforms[2].urlKey=0d944ae7-b24a-40          # webhook ?? token
dynamictp.platforms[2].secret=3a750012874bdac5c3d8b69c  # ??????????????????????????
dynamictp.platforms[2].receivers=test1,test2            # ???username / openid

dynamictp.platforms[3].platform=email                   # ??????????
dynamictp.platforms[3].platformId=4                     # ??id????
dynamictp.platforms[3].receivers=123456@qq.com,789789@qq.com # ?????????????

# ????
dynamictp.globalExecutorProps.rejectedHandlerType=CallerRunsPolicy
dynamictp.globalExecutorProps.queueType=VariableLinkedBlockingQueue
dynamictp.globalExecutorProps.waitForTasksToCompleteOnShutdown=true
dynamictp.globalExecutorProps.awaitTerminationSeconds=3
dynamictp.globalExecutorProps.taskWrapperNames=swTrace,ttl,mdc
dynamictp.globalExecutorProps.queueTimeout=300
dynamictp.globalExecutorProps.runTimeout=300
# ????????
dynamictp.globalExecutorProps.notifyItems[0].type=change
dynamictp.globalExecutorProps.notifyItems[0].silencePeriod=120

# ?????????
dynamictp.globalExecutorProps.notifyItems[1].type=capacity
dynamictp.globalExecutorProps.notifyItems[1].threshold=80
dynamictp.globalExecutorProps.notifyItems[1].count=2
dynamictp.globalExecutorProps.notifyItems[1].period=30
dynamictp.globalExecutorProps.notifyItems[1].silencePeriod=0

# ???????
dynamictp.globalExecutorProps.notifyItems[2].type=liveness
dynamictp.globalExecutorProps.notifyItems[2].threshold=80
dynamictp.globalExecutorProps.notifyItems[2].count=3
dynamictp.globalExecutorProps.notifyItems[2].period=30
dynamictp.globalExecutorProps.notifyItems[2].silencePeriod=0

# ????????
dynamictp.globalExecutorProps.notifyItems[3].type=reject
dynamictp.globalExecutorProps.notifyItems[3].count=1
dynamictp.globalExecutorProps.notifyItems[3].period=30
dynamictp.globalExecutorProps.notifyItems[3].silencePeriod=0

# ????????
dynamictp.globalExecutorProps.notifyItems[4].type=run_timeout
dynamictp.globalExecutorProps.notifyItems[4].count=20
dynamictp.globalExecutorProps.notifyItems[4].period=30
dynamictp.globalExecutorProps.notifyItems[4].silencePeriod=30

# ????????
dynamictp.globalExecutorProps.notifyItems[5].type=queue_timeout
dynamictp.globalExecutorProps.notifyItems[5].count=5
dynamictp.globalExecutorProps.notifyItems[5].period=30
dynamictp.globalExecutorProps.notifyItems[5].silencePeriod=0

# ?????
dynamictp.executors[0].threadPoolName=dtpExecutor1         # ????????
dynamictp.executors[0].threadPoolAliasName=?????        # ????????
dynamictp.executors[0].executorType=common                 # ????? common?eager?ordered?scheduled?priority??? common
dynamictp.executors[0].corePoolSize=6                      # ????????1
dynamictp.executors[0].maximumPoolSize=8                   # ????????cpu??
dynamictp.executors[0].queueCapacity=2000                  # ???????1024
dynamictp.executors[0].queueType=VariableLinkedBlockingQueue         # ?????????QueueTypeEnum??????VariableLinkedBlockingQueue
dynamictp.executors[0].rejectedHandlerType=CallerRunsPolicy          # ???????RejectedTypeEnum??????AbortPolicy
dynamictp.executors[0].keepAliveTime=60                              # ?????????????60
dynamictp.executors[0].threadNamePrefix=test                         # ????????dtp
dynamictp.executors[0].allowCoreThreadTimeOut=false                  # ??????????????false
dynamictp.executors[0].waitForTasksToCompleteOnShutdown=true         # ??spring????????????????true
dynamictp.executors[0].awaitTerminationSeconds=5                     # ??????????????????????????3????s?
dynamictp.executors[0].preStartAllCoreThreads=false                  # ?????????????false
dynamictp.executors[0].runTimeout=200                                # ????????????ms????0?????
dynamictp.executors[0].queueTimeout=100                              # ???????????????ms????0?????
dynamictp.executors[0].taskWrapperNames=ttl,mdc                      # ??????????TaskWrapper??
dynamictp.executors[0].notifyEnabled=true                            # ?????????true
dynamictp.executors[0].platformIds=1,2